version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: finance_backend
    volumes:
      - ./backend:/app
    command: sleep infinity
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: finance_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mobile:
    image: node:20
    container_name: finance_mobile
    working_dir: /app
    volumes:
      - ./mobile:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start"
    ports:
      - "19000:19000" # Expo web UI
      - "19001:19001" # Expo tunnel (LAN)
      - "19002:19002" # Expo debugger
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - API_URL=http://backend:8000

volumes:
  postgres_data:
