# Generated by Django 5.2.6 on 2025-09-08 18:15

from django.db import migrations

# A list of default categories to be created
# We include common expenses and income types
DEFAULT_CATEGORIES = [
    # Expenses
    {"name": "Groceries", "type": "expense", "color": "#FAD02E"},
    {"name": "Rent/Mortgage", "type": "expense", "color": "#E63946"},
    {"name": "Utilities", "type": "expense", "color": "#457B9D"},
    {"name": "Transport", "type": "expense", "color": "#A8DADC"},
    {"name": "Dining Out", "type": "expense", "color": "#F4A261"},
    {"name": "Shopping", "type": "expense", "color": "#9B5DE5"},
    {"name": "Health", "type": "expense", "color": "#2A9D8F"},
    {"name": "Entertainment", "type": "expense", "color": "#E76F51"},
    {"name": "Subscriptions", "type": "expense", "color": "#6D6875"},
    {"name": "Other", "type": "expense", "color": "#BDB2FF"},
    # Income
    {"name": "Salary", "type": "income", "color": "#2A9D8F"},
    {"name": "Bonus", "type": "income", "color": "#80ED99"},
    {"name": "Investment", "type": "income", "color": "#57CC99"},
    {"name": "Other Income", "type": "income", "color": "#C7F9CC"},
]


def create_default_categories(apps, schema_editor):
    """
    This function gets the Category model and creates the default entries.
    We use `get_or_create` to prevent creating duplicates if the migration
    is ever run more than once.
    """
    Category = apps.get_model("finance", "Category")
    for cat_data in DEFAULT_CATEGORIES:
        Category.objects.get_or_create(
            name=cat_data["name"],
            defaults={
                "type": cat_data["type"],
                "color": cat_data["color"],
                "user": None,  # This makes it a system category
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0003_alter_category_user",
        ),  # Make sure this matches your previous migration file
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
