# Generated by Django 5.2.6 on 2025-09-08 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_seed_default_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringtransaction",
            name="active",
        ),
        migrations.RemoveField(
            model_name="recurringtransaction",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="recurringtransaction",
            name="interval",
        ),
        migrations.AddField(
            model_name="recurringtransaction",
            name="notes",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="recurringtransaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finance.account"
            ),
        ),
        migrations.AlterField(
            model_name="recurringtransaction",
            name="frequency",
            field=models.CharField(
                choices=[("monthly", "Monthly")], default="monthly", max_length=10
            ),
        ),
    ]
