# Generated by Django 5.2.6 on 2025-09-08 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_remove_recurringtransaction_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringtransaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_transactions",
                to="finance.account",
            ),
        ),
        migrations.AlterField(
            model_name="recurringtransaction",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="monthly",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="recurringtransaction",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
