name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: finance_user
          POSTGRES_PASSWORD: finance_pass
          POSTGRES_DB: finance_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U finance_user -d finance_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Run linters
        run: pre-commit run --all-files

      - name: Run tests
        run: pytest --disable-warnings --maxfail=1
